version: "3.9"
services:
  db:
    container_name: db-dmix
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - $PWD/db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dmix_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel1234
    networks:
      - net-dmix
  web:
    container_name: dmix-web
    depends_on:
      - db
    ports:
      - "8081:80"
    volumes:
      - "$PWD/web:/var/www/html"
      - "$PWD/httpd.conf:/etc/httpd/conf/httpd.conf"
    image: laravel-php8
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net-dmix
networks:
  net-dmix:
    
